### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: bogus opcode: 0073

### ISSUE THREAD

**Issue by greathh** [dqzg12300/dexfixer#4]
请问下执行报错怎么解决呢
Exception in thread "main" java.lang.IllegalArgumentException: bogus opcode: 0073
        at com.android.dx.io.OpcodeInfo.get(OpcodeInfo.java:1227)
        at com.android.dx.io.OpcodeInfo.getFormat(OpcodeInfo.java:1242)
        at com.android.dx.io.instructions.DecodedInstruction.decode(DecodedInstruction.java:72)
        at com.android.dx.io.instructions.DecodedInstruction.decodeAll(DecodedInstruction.java:89)
        at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:46)
        at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:951)
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:892)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:862)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:759)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:613)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:180)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:207)
        at com.android.dx.unpacker.DexFixer.main(DexFixer.java:45)

**Comment by Rungjen** [comment]
和我的报错一模一样，估计是dex文件与bin文件有问题，老哥解决没？

**Comment by greathh** [comment]
您好，您所发送的邮件已收到。感谢来信。
 
 
Hello, your email has been received.
 
 
祝您生活愉快。

**Comment by yys-nixiang** [comment]
解决了吗，我遇到了现在，可以帮助我吗

**Comment by greathh** [comment]
您好，您所发送的邮件已收到。感谢来信。
 
 
Hello, your email has been received.
 
 
祝您生活愉快。
