### ISSUE TITLE
修复的时候出现了错误

### ISSUE THREAD

**Issue by misslng** [dqzg12300/dexfixer#5]
Unterminated object at line 1 column 249 path $.ins
看着不像是bin文件的问题
老哥有遇到过吗

**Comment by misslng** [comment]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 249 path $.ins
        at com.google.gson.Gson.fromJson(Gson.java:902)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at com.android.dx.unpacker.MethodCodeItemFile.<init>(MethodCodeItemFile.java:45)
        at com.android.dx.unpacker.DexFixer.main(DexFixer.java:43)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 249 path $.ins
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        ... 5 more
这是完整的报错

**Comment by dqzg12300** [comment]
是不是格式不对

**Comment by OrientalGlass** [comment]
我也遇到了该问题,使用的并非原版fart,而是r0ysue的fart8终极版,参考[FART8终极版发布，欢迎尝鲜体验](https://zhuanlan.zhihu.com/p/573577231)
该版本fart生成的bin文件的json已经使用双引号包裹了数据,所以dexfixer解析json时会出现多的双引号导致出错
注释MethodCodeItemFile的replace代码即可
<img width="1920" height="1030" alt="Image" src="https://github.com/user-attachments/assets/f1e521da-8421-40df-a1be-46c8514adcbb" />

**Comment by misslng** [comment]
> 我也遇到了该问题,使用的并非原版fart,而是r0ysue的fart8终极版,参考[FART8终极版发布，欢迎尝鲜体验](https://zhuanlan.zhihu.com/p/573577231) 该版本fart生成的bin文件的json已经使用双引号包裹了数据,所以dexfixer解析json时会出现多的双引号导致出错 注释MethodCodeItemFile的replace代码即可 <img alt="Image" width="1920" height="1030" src="https://private-user-images.githubusercontent.com/99623557/493258840-f1e521da-8421-40df-a1be-46c8514adcbb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg3ODE4NzMsIm5iZiI6MTc1ODc4MTU3MywicGF0aCI6Ii85OTYyMzU1Ny80OTMyNTg4NDAtZjFlNTIxZGEtODQyMS00MGRmLWExYmUtNDZjODUxNGFkY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI1VDA2MjYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2N2Q2Yjg4YTE1ZTMxZmI2MmJhZWMyZDdkZjdjYzczYTdkODQ0MjhjM2YyMTMyMDUzMDYyNGEyZDc5ZDU1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kSlgipnWuRbilJXcyVAEtSuJlFFkbIsxiZBwnk9NBtk">

嗯嗯，之前已经处理好了，感谢回复
